# Generated by Django 4.2.6 on 2023-11-21 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_user_id_alter_todo_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='User_id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2023, 11, 21, 12, 30, 16, 213100)),
        ),
    ]
